var data = {"ProductData":
    [
 {
   "SKU": 523456789,
   "ProductName": "Basic Black Skinny",
   "Picture": "basicblackskinny.jpg",
   "SubCategory": "Jeans",
   "Color": "Black",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 41,
   "MarginGroup": "None",
   "Volume": 201,
   "VolumeGroup": "Bottom",
   "Sell Thru": 35,
   "Sell ThruGroup": "None",
   "RemainingInv": 574,
   "RemainingInvGroup": "None",
   "Time": "winter17"
 },
 {
   "SKU": 523456790,
   "ProductName": "Carrot Fit Jean",
   "Picture": "blackslim.jpg",
   "SubCategory": "Jeans",
   "Color": "Black",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 60,
   "MarginGroup": "Top",
   "Volume": 1300,
   "VolumeGroup": "Top",
   "Sell Thru": 65,
   "Sell ThruGroup": "Top",
   "RemainingInv": 2000,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 523456791,
   "ProductName": "Blue Basic Jean",
   "Picture": "bluebasicjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 22,
   "MarginGroup": "None",
   "Volume": 1400,
   "VolumeGroup": "Top",
   "Sell Thru": 40,
   "Sell ThruGroup": "None",
   "RemainingInv": 3500,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 523456792,
   "ProductName": "Blue Jogger",
   "Picture": "bluejogger.jpg",
   "SubCategory": "Joggers",
   "Color": "Blue",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "Linen",
   "Vendor": "789 Vendor",
   "Margin": 34,
   "MarginGroup": "Top",
   "Volume": 480,
   "VolumeGroup": "None",
   "Sell Thru": 24,
   "Sell ThruGroup": "None",
   "RemainingInv": 2000,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456789,
   "ProductName": "Straight Dark Salvaged Jean",
   "Picture": "bluestraight.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Rinse",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 18,
   "MarginGroup": "Bottom",
   "Volume": 300,
   "VolumeGroup": "Bottom",
   "Sell Thru": 20,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1500,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 523456790,
   "ProductName": "Blue Suit Pant",
   "Picture": "bluesuit.jpg",
   "SubCategory": "Suits",
   "Color": "Blue",
   "Style": "Pleated",
   "Wash": "None",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 25,
   "MarginGroup": "None",
   "Volume": 401,
   "VolumeGroup": "Bottom",
   "Sell Thru": 85,
   "Sell ThruGroup": "None",
   "RemainingInv": 472,
   "RemainingInvGroup": "None",
   "Time": "July31"
 },
 {
   "SKU": 523456791,
   "ProductName": "Camo Trouser",
   "Picture": "camotrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Pattern",
   "Style": "Straight",
   "Wash": "None",
   "Details": "Camo",
   "Vendor": "ABC Vendor",
   "Margin": 23,
   "MarginGroup": "Top",
   "Volume": 465,
   "VolumeGroup": "None",
   "Sell Thru": 24,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1938,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456792,
   "ProductName": "Checked Suit Pant",
   "Picture": "checked.jpg",
   "SubCategory": "Suits",
   "Color": "Blue",
   "Style": "Cropped",
   "Wash": "None",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 26,
   "MarginGroup": "None",
   "Volume": 428,
   "VolumeGroup": "Bottom",
   "Sell Thru": 30,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1427,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456793,
   "ProductName": "Checked Suit Pant",
   "Picture": "checkedsuit.jpg",
   "SubCategory": "Suits",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "None",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 13,
   "MarginGroup": "Bottom",
   "Volume": 327,
   "VolumeGroup": "Bottom",
   "Sell Thru": 66,
   "Sell ThruGroup": "Top",
   "RemainingInv": 495,
   "RemainingInvGroup": "None",
   "Time": "spring17"
 },
 {
   "SKU": 523456794,
   "ProductName": "Khaki Chino",
   "Picture": "chinokhalki.jpg",
   "SubCategory": "Trousers",
   "Color": "Tan",
   "Style": "Straight",
   "Wash": "None",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 34,
   "MarginGroup": "Top",
   "Volume": 327,
   "VolumeGroup": "Bottom",
   "Sell Thru": 56,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 584,
   "RemainingInvGroup": "None",
   "Time": "spring17"
 },
 {
   "SKU": 523456795,
   "ProductName": "Contrasting Suit Pant",
   "Picture": "contrastingsuit.jpg",
   "SubCategory": "Suits",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "None",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 15,
   "MarginGroup": "Bottom",
   "Volume": 1373,
   "VolumeGroup": "Top",
   "Sell Thru": 43,
   "Sell ThruGroup": "None",
   "RemainingInv": 3193,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456796,
   "ProductName": "Dark Ripped Jean",
   "Picture": "darkrippedjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 22,
   "MarginGroup": "Top",
   "Volume": 180,
   "VolumeGroup": "Bottom",
   "Sell Thru": 20,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 900,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 523456797,
   "ProductName": "Dark Slim Jean",
   "Picture": "darkslimjean.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 50,
   "MarginGroup": "Top",
   "Volume": 175,
   "VolumeGroup": "Bottom",
   "Sell Thru": 47,
   "Sell ThruGroup": "Top",
   "RemainingInv": 372,
   "RemainingInvGroup": "Bottom",
   "Time": "July31"
 },
 {
   "SKU": 523456798,
   "ProductName": "Denim Chino",
   "Picture": "denimchinos.jpg",
   "SubCategory": "Trousers",
   "Color": "Green",
   "Style": "Straight",
   "Wash": "None",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 24,
   "MarginGroup": "None",
   "Volume": 1191,
   "VolumeGroup": "Top",
   "Sell Thru": 34,
   "Sell ThruGroup": "None",
   "RemainingInv": 3503,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456799,
   "ProductName": "Desert Jean",
   "Picture": "desertjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 8,
   "MarginGroup": "None",
   "Volume": 925,
   "VolumeGroup": "Top",
   "Sell Thru": 65,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1423,
   "RemainingInvGroup": "Top",
   "Time": "July31"
 },
 {
   "SKU": 523456800,
   "ProductName": "Embroidered Jean",
   "Picture": "embroideredjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "Patches",
   "Vendor": "123 Vendor",
   "Margin": 30,
   "MarginGroup": "Top",
   "Volume": 510,
   "VolumeGroup": "None",
   "Sell Thru": 22,
   "Sell ThruGroup": "Top",
   "RemainingInv": 2318,
   "RemainingInvGroup": "Top",
   "Time": "July 31"
 },
 {
   "SKU": 523456801,
   "ProductName": "Faded Jean",
   "Picture": "fadedjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Faded",
   "Details": "Ripped",
   "Vendor": "123 Vendor",
   "Margin": 30,
   "MarginGroup": "Bottom",
   "Volume": 238,
   "VolumeGroup": "Bottom",
   "Sell Thru": 46,
   "Sell ThruGroup": "None",
   "RemainingInv": 517,
   "RemainingInvGroup": "None",
   "Time": "winter17"
 },
 {
   "SKU": 523456802,
   "ProductName": "Grey Faded Jean",
   "Picture": "grayfadedjean.jpg",
   "SubCategory": "Jeans",
   "Color": "Grey",
   "Style": "Straight",
   "Wash": "Faded",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 35,
   "MarginGroup": "None",
   "Volume": 385,
   "VolumeGroup": "Bottom",
   "Sell Thru": 32,
   "Sell ThruGroup": "None",
   "RemainingInv": 1203,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456803,
   "ProductName": "Grey Faded Jean",
   "Picture": "grayfadedjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Grey",
   "Style": "Straight",
   "Wash": "Faded",
   "Details": "Ripped",
   "Vendor": "123 Vendor",
   "Margin": 30,
   "MarginGroup": "Top",
   "Volume": 553,
   "VolumeGroup": "None",
   "Sell Thru": 35,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1580,
   "RemainingInvGroup": "Top",
   "Time": "July31"
 },
 {
   "SKU": 523456804,
   "ProductName": "Grey Jean",
   "Picture": "grayjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Grey",
   "Style": "Straight",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 23,
   "MarginGroup": "Bottom",
   "Volume": 793,
   "VolumeGroup": "Top",
   "Sell Thru": 65,
   "Sell ThruGroup": "Top",
   "RemainingInv": 1220,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456805,
   "ProductName": "Grey Patches Jean",
   "Picture": "graypatches.jpg",
   "SubCategory": "Jeans",
   "Color": "Grey",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "Patches",
   "Vendor": "789 Vendor",
   "Margin": 49,
   "MarginGroup": "Top",
   "Volume": 920,
   "VolumeGroup": "Top",
   "Sell Thru": 46,
   "Sell ThruGroup": "Top",
   "RemainingInv": 2000,
   "RemainingInvGroup": "Top",
   "Time": "July31"
 },
 {
   "SKU": 523456806,
   "ProductName": "Grey Plush Jogger",
   "Picture": "grayplushjoggers.jpg",
   "SubCategory": "Joggers",
   "Color": "Grey",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "Plush",
   "Vendor": "789 Vendor",
   "Margin": 25,
   "MarginGroup": "None",
   "Volume": 769,
   "VolumeGroup": "Top",
   "Sell Thru": 51,
   "Sell ThruGroup": "None",
   "RemainingInv": 1508,
   "RemainingInvGroup": "Top",
   "Time": "July31"
 },
 {
   "SKU": 523456807,
   "ProductName": "Grey Slim Jean",
   "Picture": "grayslimfit.jpg",
   "SubCategory": "Jeans",
   "Color": "Grey",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 24,
   "MarginGroup": "Top",
   "Volume": 359,
   "VolumeGroup": "Bottom",
   "Sell Thru": 22,
   "Sell ThruGroup": "Top",
   "RemainingInv": 1632,
   "RemainingInvGroup": "Top",
   "Time": "July31"
 },
 {
   "SKU": 523456808,
   "ProductName": "Grey Trouser",
   "Picture": "graytrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Grey",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Cuffed",
   "Vendor": "123 Vendor",
   "Margin": 25,
   "MarginGroup": "None",
   "Volume": 568,
   "VolumeGroup": "None",
   "Sell Thru": 25,
   "Sell ThruGroup": "Top",
   "RemainingInv": 2272,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456809,
   "ProductName": "Grey Jogger",
   "Picture": "jogger.jpg",
   "SubCategory": "Joggers",
   "Color": "Grey",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "Linen",
   "Vendor": "789 Vendor",
   "Margin": 34,
   "MarginGroup": "Top",
   "Volume": 557,
   "VolumeGroup": "None",
   "Sell Thru": 34,
   "Sell ThruGroup": "Top",
   "RemainingInv": 1638,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456810,
   "ProductName": "Khaki Zip Trouser",
   "Picture": "khalkizips.jpg",
   "SubCategory": "Trousers",
   "Color": "Green",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Zippers",
   "Vendor": "123 Vendor",
   "Margin": 35,
   "MarginGroup": "None",
   "Volume": 789,
   "VolumeGroup": "Top",
   "Sell Thru": 13,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 6069,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456811,
   "ProductName": "Kneecap Jean",
   "Picture": "kneecapjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "Ripped, Patches",
   "Vendor": "ABC Vendor",
   "Margin": 45,
   "MarginGroup": "None",
   "Volume": 262,
   "VolumeGroup": "Bottom",
   "Sell Thru": 46,
   "Sell ThruGroup": "None",
   "RemainingInv": 570,
   "RemainingInvGroup": "None",
   "Time": "winter17"
 },
 {
   "SKU": 523456812,
   "ProductName": "Lavender Trouser",
   "Picture": "lavendertrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Blue",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Cuffed",
   "Vendor": "123 Vendor",
   "Margin": 23,
   "MarginGroup": "None",
   "Volume": 108,
   "VolumeGroup": "Bottom",
   "Sell Thru": 9,
   "Sell ThruGroup": "None",
   "RemainingInv": 1200,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456813,
   "ProductName": "Light Blue Jean",
   "Picture": "lightbluejeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 66,
   "MarginGroup": "None",
   "Volume": 399,
   "VolumeGroup": "Bottom",
   "Sell Thru": 33,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1209,
   "RemainingInvGroup": "Top",
   "Time": "July31"
 },
 {
   "SKU": 523456814,
   "ProductName": "Light Faded Jean",
   "Picture": "lightfadedjean.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Faded",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 40,
   "MarginGroup": "None",
   "Volume": 724,
   "VolumeGroup": "None",
   "Sell Thru": 37,
   "Sell ThruGroup": "None",
   "RemainingInv": 1957,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 523456815,
   "ProductName": "Light Ripped Jean",
   "Picture": "lightrippedjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "Ripped",
   "Vendor": "ABC Vendor",
   "Margin": 30,
   "MarginGroup": "Bottom",
   "Volume": 148,
   "VolumeGroup": "Bottom",
   "Sell Thru": 87,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 170,
   "RemainingInvGroup": "Bottom",
   "Time": "July31"
 },
 {
   "SKU": 523456816,
   "ProductName": "Light Raw Jean",
   "Picture": "lightrippedraw.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "Light",
   "Details": "Ripped",
   "Vendor": "XYZ Vendor",
   "Margin": 34,
   "MarginGroup": "None",
   "Volume": 575,
   "VolumeGroup": "None",
   "Sell Thru": 31,
   "Sell ThruGroup": "None",
   "RemainingInv": 1855,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 523456817,
   "ProductName": "Light Slim Jean",
   "Picture": "lightslimjean.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "Light",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 47,
   "MarginGroup": "Top",
   "Volume": 246,
   "VolumeGroup": "Bottom",
   "Sell Thru": 44,
   "Sell ThruGroup": "None",
   "RemainingInv": 559,
   "RemainingInvGroup": "None",
   "Time": "July31"
 },
 {
   "SKU": 523456818,
   "ProductName": "Light Twist Jean",
   "Picture": "lighttwist.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "Ripped",
   "Vendor": "XYZ Vendor",
   "Margin": 26,
   "MarginGroup": "None",
   "Volume": 293,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1274,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 523456819,
   "ProductName": "Patches Jean",
   "Picture": "patchesjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "Ripped, Patches",
   "Vendor": "ABC Vendor",
   "Margin": 30,
   "MarginGroup": "Bottom",
   "Volume": 342,
   "VolumeGroup": "Bottom",
   "Sell Thru": 88,
   "Sell ThruGroup": "None",
   "RemainingInv": 389,
   "RemainingInvGroup": "Bottom",
   "Time": "July31"
 },
 {
   "SKU": 523456820,
   "ProductName": "Pleated Jogger",
   "Picture": "pleated.jpg",
   "SubCategory": "Joggers",
   "Color": "Blue",
   "Style": "Cropped",
   "Wash": "None",
   "Details": "Linen",
   "Vendor": "789 Vendor",
   "Margin": 23,
   "MarginGroup": "Bottom",
   "Volume": 823,
   "VolumeGroup": "Top",
   "Sell Thru": 34,
   "Sell ThruGroup": "None",
   "RemainingInv": 2421,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456821,
   "ProductName": "Plush Trouser",
   "Picture": "plushtrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Blue",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 43,
   "MarginGroup": "None",
   "Volume": 451,
   "VolumeGroup": "None",
   "Sell Thru": 23,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1961,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 523456822,
   "ProductName": "Raw Edge Jean",
   "Picture": "rawedge.jpg",
   "SubCategory": "Jeans",
   "Color": "Black",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 17,
   "MarginGroup": "Bottom",
   "Volume": 440,
   "VolumeGroup": "Bottom",
   "Sell Thru": 22,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 2000,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 523456823,
   "ProductName": "Raw Ripped Jean",
   "Picture": "rawrippedjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "Ripped",
   "Vendor": "ABC Vendor",
   "Margin": 30,
   "MarginGroup": "None",
   "Volume": 264,
   "VolumeGroup": "Bottom",
   "Sell Thru": 43,
   "Sell ThruGroup": "None",
   "RemainingInv": 614,
   "RemainingInvGroup": "None",
   "Time": "July31"
 },
 {
   "SKU": 523456824,
   "ProductName": "Red Trouser",
   "Picture": "redtrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Red",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Cuffed",
   "Vendor": "XYZ Vendor",
   "Margin": 24,
   "MarginGroup": "Top",
   "Volume": 345,
   "VolumeGroup": "Bottom",
   "Sell Thru": 45,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 767,
   "RemainingInvGroup": "Top",
   "Time": "July31"
 },
 {
   "SKU": 523456825,
   "ProductName": "Regular Basic Blue Jean",
   "Picture": "regularbasicblue.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 28,
   "MarginGroup": "Bottom",
   "Volume": 171,
   "VolumeGroup": "Bottom",
   "Sell Thru": 25,
   "Sell ThruGroup": "None",
   "RemainingInv": 684,
   "RemainingInvGroup": "None",
   "Time": "winter17"
 },
 {
   "SKU": 523456826,
   "ProductName": "Regular Basic Jean",
   "Picture": "regularbasicjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Black",
   "Style": "Straight",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 43,
   "MarginGroup": "None",
   "Volume": 525,
   "VolumeGroup": "None",
   "Sell Thru": 40,
   "Sell ThruGroup": "None",
   "RemainingInv": 1313,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 323456789,
   "ProductName": "Weekday Blue Jean",
   "Picture": "regularblue.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 42,
   "MarginGroup": "None",
   "Volume": 800,
   "VolumeGroup": "Top",
   "Sell Thru": 50,
   "Sell ThruGroup": "Top",
   "RemainingInv": 1600,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 323456790,
   "ProductName": "Ripped Pleated Jean",
   "Picture": "rippedpleatsjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "Mid",
   "Details": "Ripped",
   "Vendor": "ABC Vendor",
   "Margin": 23,
   "MarginGroup": "Top",
   "Volume": 144,
   "VolumeGroup": "Bottom",
   "Sell Thru": 11,
   "Sell ThruGroup": "None",
   "RemainingInv": 1309,
   "RemainingInvGroup": "Top",
   "Time": "July31"
 },
 {
   "SKU": 323456791,
   "ProductName": "Seersucker Suit",
   "Picture": "seersucker.jpg ",
   "SubCategory": "Suits",
   "Color": "Blue",
   "Style": "Cropped",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 35,
   "MarginGroup": "None",
   "Volume": 360,
   "VolumeGroup": "Bottom",
   "Sell Thru": 34,
   "Sell ThruGroup": "None",
   "RemainingInv": 1059,
   "RemainingInvGroup": "Top",
   "Time": "winter18"
 },
 {
   "SKU": 323456792,
   "ProductName": "Selvedge Jean",
   "Picture": "selvedge.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 20,
   "MarginGroup": "Bottom",
   "Volume": 243,
   "VolumeGroup": "Bottom",
   "Sell Thru": 17,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1429,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 323456793,
   "ProductName": "Pink Skinny Trouser",
   "Picture": "skinnytrouserpink.jpg",
   "SubCategory": "Trousers",
   "Color": "Pink",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Cuffed",
   "Vendor": "XYZ Vendor",
   "Margin": 55,
   "MarginGroup": "Top",
   "Volume": 714,
   "VolumeGroup": "None",
   "Sell Thru": 2,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 35700,
   "RemainingInvGroup": "Top",
   "Time": "winter18"
 },
 {
   "SKU": 323456794,
   "ProductName": "Blue Skinny Trouser",
   "Picture": "skinnytrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Blue",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Cuffed",
   "Vendor": "XYZ Vendor",
   "Margin": 33,
   "MarginGroup": "Bottom",
   "Volume": 751,
   "VolumeGroup": "Top",
   "Sell Thru": 45,
   "Sell ThruGroup": "None",
   "RemainingInv": 1669,
   "RemainingInvGroup": "Top",
   "Time": "winter18"
 },
 {
   "SKU": 323456795,
   "ProductName": "Skull Suit Pant",
   "Picture": "skullsuit.jpg",
   "SubCategory": "Suits",
   "Color": "Pattern",
   "Style": "Cropped",
   "Wash": "None",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 25,
   "MarginGroup": "None",
   "Volume": 197,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 857,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 323456796,
   "ProductName": "Slim Dark Jean",
   "Picture": "slimdarkbluejeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 23,
   "MarginGroup": "Top",
   "Volume": 323,
   "VolumeGroup": "Bottom",
   "Sell Thru": 43,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 751,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 323456797,
   "ProductName": "Slim Dark Trouser",
   "Picture": "slimfitdark.jpg",
   "SubCategory": "Trousers",
   "Color": "Black",
   "Style": "Slim",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 10,
   "MarginGroup": "Top",
   "Volume": 153,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "Top",
   "RemainingInv": 665,
   "RemainingInvGroup": "None",
   "Time": "July31"
 },
 {
   "SKU": 323456798,
   "ProductName": "Slim Grey Trouser",
   "Picture": "slimfitgray.jpg",
   "SubCategory": "Trousers",
   "Color": "Grey",
   "Style": "Slim",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 13,
   "MarginGroup": "Bottom",
   "Volume": 10,
   "VolumeGroup": "Bottom",
   "Sell Thru": 22,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 45,
   "RemainingInvGroup": "Bottom",
   "Time": "winter18"
 },
 {
   "SKU": 323456799,
   "ProductName": "Slim Navy Trouser",
   "Picture": "slimfitnavy.jpg",
   "SubCategory": "Trousers",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 13,
   "MarginGroup": "Top",
   "Volume": 449,
   "VolumeGroup": "Bottom",
   "Sell Thru": 11,
   "Sell ThruGroup": "None",
   "RemainingInv": 4082,
   "RemainingInvGroup": "Top",
   "Time": "July24"
 },
 {
   "SKU": 323456800,
   "ProductName": "Slim Tan Trouser",
   "Picture": "slimfittan.jpg",
   "SubCategory": "Trousers",
   "Color": "Tan",
   "Style": "Slim",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 13,
   "MarginGroup": "None",
   "Volume": 234,
   "VolumeGroup": "Bottom",
   "Sell Thru": 8,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 2925,
   "RemainingInvGroup": "Top",
   "Time": "July24"
 },
 {
   "SKU": 323456801,
   "ProductName": "Slimfit White Jean",
   "Picture": "slimfitwhite.jpg",
   "SubCategory": "Jeans",
   "Color": "White",
   "Style": "Slim",
   "Wash": "Light",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 18,
   "MarginGroup": "None",
   "Volume": 394,
   "VolumeGroup": "Bottom",
   "Sell Thru": 21,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1876,
   "RemainingInvGroup": "Top",
   "Time": "July24"
 },
 {
   "SKU": 223456789,
   "ProductName": "Slim Grey Flex Jean",
   "Picture": "slimgray.jpg",
   "SubCategory": "Jeans",
   "Color": "Grey",
   "Style": "Slim",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 55,
   "MarginGroup": "Top",
   "Volume": 1000,
   "VolumeGroup": "Top",
   "Sell Thru": 60,
   "Sell ThruGroup": "Top",
   "RemainingInv": 1667,
   "RemainingInvGroup": "Top",
   "Time": "July31"
 },
 {
   "SKU": 223456790,
   "ProductName": "Carrot Fit Jean",
   "Picture": "slimjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 11,
   "MarginGroup": "None",
   "Volume": 127,
   "VolumeGroup": "Bottom",
   "Sell Thru": 10,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1270,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 223456791,
   "ProductName": "Slim Vintage Jean",
   "Picture": "slimvintage.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 39,
   "MarginGroup": "None",
   "Volume": 613,
   "VolumeGroup": "None",
   "Sell Thru": 36,
   "Sell ThruGroup": "None",
   "RemainingInv": 1703,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 123456789,
   "ProductName": "Stretch Jean",
   "Picture": "stretch.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "Light",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 30,
   "MarginGroup": "None",
   "Volume": 200,
   "VolumeGroup": "Bottom",
   "Sell Thru": 30,
   "Sell ThruGroup": "None",
   "RemainingInv": 667,
   "RemainingInvGroup": "None",
   "Time": "winter17"
 },
 {
   "SKU": 123456790,
   "ProductName": "Studio Jean",
   "Picture": "studiojeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 23,
   "MarginGroup": "None",
   "Volume": 252,
   "VolumeGroup": "Bottom",
   "Sell Thru": 13,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1938,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 123456791,
   "ProductName": "Slim Tan Chino",
   "Picture": "tanchinos.jpg",
   "SubCategory": "Trousers",
   "Color": "Tan",
   "Style": "Cropped",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 14,
   "MarginGroup": "None",
   "Volume": 368,
   "VolumeGroup": "Bottom",
   "Sell Thru": 55,
   "Sell ThruGroup": "None",
   "RemainingInv": 669,
   "RemainingInvGroup": "None",
   "Time": "July24"
 },
 {
   "SKU": 123456792,
   "ProductName": "Tan Trouser",
   "Picture": "tantrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Tan",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Cuffed",
   "Vendor": "XYZ Vendor",
   "Margin": 15,
   "MarginGroup": "Bottom",
   "Volume": 115,
   "VolumeGroup": "Bottom",
   "Sell Thru": 76,
   "Sell ThruGroup": "None",
   "RemainingInv": 151,
   "RemainingInvGroup": "Bottom",
   "Time": "July24"
 },
 {
   "SKU": 123456793,
   "ProductName": "Tech Jogger",
   "Picture": "techjogger.jpg",
   "SubCategory": "Joggers",
   "Color": "Black",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "Cotton",
   "Vendor": "789 Vendor",
   "Margin": 23,
   "MarginGroup": "Top",
   "Volume": 231,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1004,
   "RemainingInvGroup": "Top",
   "Time": "July31"
 },
 {
   "SKU": 435456789,
   "ProductName": "Black Traveller Jean",
   "Picture": "traveler.jpg",
   "SubCategory": "Jeans",
   "Color": "Black",
   "Style": "Slim",
   "Wash": "Rinse",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 53,
   "MarginGroup": "Top",
   "Volume": 500,
   "VolumeGroup": "None",
   "Sell Thru": 40,
   "Sell ThruGroup": "Top",
   "RemainingInv": 1250,
   "RemainingInvGroup": "None",
   "Time": "winter17"
 },
 {
   "SKU": 435456790,
   "ProductName": "Twist Jean",
   "Picture": "twistjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "Ripped",
   "Vendor": "789 Vendor",
   "Margin": 24,
   "MarginGroup": "None",
   "Volume": 175,
   "VolumeGroup": "Bottom",
   "Sell Thru": 15,
   "Sell ThruGroup": "Top",
   "RemainingInv": 1167,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 435456791,
   "ProductName": "White Trouser",
   "Picture": "white.jpg",
   "SubCategory": "Trousers",
   "Color": "White",
   "Style": "Straight",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 15,
   "MarginGroup": "Bottom",
   "Volume": 850,
   "VolumeGroup": "Top",
   "Sell Thru": 90,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 944,
   "RemainingInvGroup": "Top",
   "Time": "July24"
 },
 {
   "SKU": 435456792,
   "ProductName": "White Jogger",
   "Picture": "whitejogger.jpg",
   "SubCategory": "Joggers",
   "Color": "White",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "Linen",
   "Vendor": "ABC Vendor",
   "Margin": 23,
   "MarginGroup": "Bottom",
   "Volume": 363,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "None",
   "RemainingInv": 1578,
   "RemainingInvGroup": "Top",
   "Time": "July31"
 },
 {
   "SKU": 435456793,
   "ProductName": "White Ripped Jean",
   "Picture": "whiteripped.jpg",
   "SubCategory": "Jeans",
   "Color": "White",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "Ripped",
   "Vendor": "789 Vendor",
   "Margin": 35,
   "MarginGroup": "None",
   "Volume": 331,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 1439,
   "RemainingInvGroup": "Top",
   "Time": "spring17"
 },
 {
   "SKU": 435456794,
   "ProductName": "White Zip Trouser",
   "Picture": "whitezips.jpg",
   "SubCategory": "Trousers",
   "Color": "Green",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 15,
   "MarginGroup": "None",
   "Volume": 200,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "Top",
   "RemainingInv": 870,
   "RemainingInvGroup": "Top",
   "Time": "winter17"
 },
 {
   "SKU": 435456795,
   "ProductName": "Zip Jogger",
   "Picture": "zipjogger.jpg",
   "SubCategory": "Joggers",
   "Color": "Blue",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "Zippers",
   "Vendor": "ABC Vendor",
   "Margin": 24,
   "MarginGroup": "Top",
   "Volume": 116,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "Bottom",
   "RemainingInv": 504,
   "RemainingInvGroup": "None",
   "Time": "spring17"
 }
]}

var lookUpFilter = {
    "Jeans":{"type":"SubCategory","info":"Jeans"},
    "Suits":{"type":"SubCategory","info":"Suits"},
    "Trousers":{"type":"SubCategory","info":"Trousers"},
    "Joggers":{"type":"SubCategory","info":"Joggers"},
    
    "Volume Top 20%":{"type":"VolumeGroup","info":"Top"},
    "Volume Bottom 20%":{"type":"VolumeGroup","info":"Bottom"},
    
    "Margin Top 20%":{"type":"MarginGroup","info":"Top"},
    "Margin Bottom 20%":{"type":"MarginGroup","info":"Bottom"},
    
    "Sell Thru Top 20%":{"type":"Sell ThruGroup","info":"Top"},
    "Sell Thru Bottom 20%":{"type":"Sell ThruGroup","info":"Bottom"},
    
    "RemainingInv Top 20%":{"type":"RemainingInvGroup","info":"Top"},
    "RemainingInv Bottom 20%":{"type":"RemainingInvGroup","info":"Bottom"},
    
    "Black":{"type":"Color","info":"Black"},
    "White":{"type":"Color","info":"White"},
    "Grey":{"type":"Color","info":"Grey"},
    "Tan":{"type":"Color","info":"Tan"},
    "Blue":{"type":"Color","info":"Blue"},
    "Green":{"type":"Color","info":"Green"},
    "Red":{"type":"Color","info":"Red"},
    "Pattern":{"type":"Color","info":"Pattern"},
    
    "Slim":{"type":"Style","info":"Slim"},
    "Skinny":{"type":"Style","info":"Skinny"},
    "Straight":{"type":"Style","info":"Straight"},
    "Bootcut":{"type":"Style","info":"Bootcut"},
    "Cropped":{"type":"Style","info":"Cropped"},
    
    "Rinse":{"type":"Wash","info":"Rinse"},
    "Mid":{"type":"Wash","info":"Mid"},
    "Light":{"type":"Wash","info":"Light"},
    "Faded":{"type":"Wash","info":"Faded"},
    
    "XYZ Vendor":{"type":"Vendor","info":"XYZ Vendor"},
    "ABC Vendor":{"type":"Vendor","info":"ABC Vendor"},
    "123 Vendor":{"type":"Vendor","info":"123 Vendor"},
    "789 Vendor":{"type":"Vendor","info":"789 Vendor"},

}

var lookUpOrder ={
   "Volume High to Low":{"type": "Volume", "direction":"Descending"},
    "Volume Low to High":{"type": "Volume", "direction":"Ascending"},
    
    "Margin High to Low":{"type": "Margin", "direction":"Descending"},
    "Margin Low to High":{"type": "Margin", "direction":"Ascending"},
    
    "Sell Thru High to Low":{"type": "Sell Thru", "direction":"Descending"},
    "Sell Thru Low to High":{"type": "Sell Thru", "direction":"Ascending"},
    
    "RemainingInv High to Low":{"type": "RemainingInv", "direction":"Descending"},
    "RemainingInv Low to High":{"type": "RemainingInv", "direction":"Ascending"},
    
    "Color":{"type": "Color", "direction":"Group"},
    "Style":{"type": "Style", "direction":"Group"},
    "Wash":{"type": "Wash", "direction":"Group"},
    
    "Group by vendor":{"type": "Vendor", "direction":"Group"},
    
}



