var data = {"ProductData":
    [
 {
   "SKU": 123456789,
   "ProductName": "Stretch Jean",
   "Picture": "stretch.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "Light",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 30,
   "MarginGroup": "None",
   "Volume": 200,
   "VolumeGroup": "Bottom",
   "Sell Thru": 30,
   "Sell ThruGroup": "None",
   "Remaining Inv": 667,
   "Remaining InvGroup": "None"
 },
 {
   "SKU": 223456789,
   "ProductName": "Slim Grey Flex Jean",
   "Picture": "slimgray.jpg",
   "SubCategory": "Jeans",
   "Color": "Grey",
   "Style": "Slim",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 55,
   "MarginGroup": "Top",
   "Volume": 1000,
   "VolumeGroup": "Top",
   "Sell Thru": 60,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 1667,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 323456789,
   "ProductName": "Weekday Blue Jean",
   "Picture": "regularblue.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 42,
   "MarginGroup": "None",
   "Volume": 800,
   "VolumeGroup": "Top",
   "Sell Thru": 50,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 1600,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 435456789,
   "ProductName": "Black Traveller Jean",
   "Picture": "traveler.jpg",
   "SubCategory": "Jeans",
   "Color": "Black",
   "Style": "Slim",
   "Wash": "Rinse",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 53,
   "MarginGroup": "Top",
   "Volume": 500,
   "VolumeGroup": "None",
   "Sell Thru": 40,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 1250,
   "Remaining InvGroup": "None"
 },
 {
   "SKU": 523456789,
   "ProductName": "Straight Dark Salvaged Jean",
   "Picture": "bluestraight.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Rinse",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 18,
   "MarginGroup": "Bottom",
   "Volume": 300,
   "VolumeGroup": "Bottom",
   "Sell Thru": 20,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 1500,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456790,
   "ProductName": "Carrot Fit Jean",
   "Picture": "blackslim.jpg",
   "SubCategory": "Jeans",
   "Color": "Black",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 60,
   "MarginGroup": "Top",
   "Volume": 1300,
   "VolumeGroup": "Top",
   "Sell Thru": 65,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 2000,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456791,
   "ProductName": "Raw Edge Jean",
   "Picture": "rawedge.jpg",
   "SubCategory": "Jeans",
   "Color": "Black",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 17,
   "MarginGroup": "Bottom",
   "Volume": 440,
   "VolumeGroup": "Bottom",
   "Sell Thru": 22,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 2000,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456792,
   "ProductName": "Grey Patches Jean",
   "Picture": "graypatches.jpg",
   "SubCategory": "Jeans",
   "Color": "Black",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "Patches",
   "Vendor": "789 Vendor",
   "Margin": 49,
   "MarginGroup": "Top",
   "Volume": 920,
   "VolumeGroup": "Top",
   "Sell Thru": 46,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 2000,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456793,
   "ProductName": "Basic Black Skinny",
   "Picture": "basicblacksinny.jpg",
   "SubCategory": "Jeans",
   "Color": "Black",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 41,
   "MarginGroup": "None",
   "Volume": 655,
   "VolumeGroup": "None",
   "Sell Thru": 35,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1871,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456794,
   "ProductName": "Regular Basic Jean",
   "Picture": "regularbasicjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Black",
   "Style": "Straight",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 43,
   "MarginGroup": "None",
   "Volume": 526,
   "VolumeGroup": "None",
   "Sell Thru": 40,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1315,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456795,
   "ProductName": "Regular Basic Blue Jean",
   "Picture": "regularbasicblue.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 28,
   "MarginGroup": "Bottom",
   "Volume": 470,
   "VolumeGroup": "None",
   "Sell Thru": 25,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1880,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456796,
   "ProductName": "Selvedge Jean",
   "Picture": "selvedge.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 20,
   "MarginGroup": "Bottom",
   "Volume": 241,
   "VolumeGroup": "Bottom",
   "Sell Thru": 17,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 1418,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456797,
   "ProductName": "Slim Vintage Jean",
   "Picture": "slimvintage.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 39,
   "MarginGroup": "None",
   "Volume": 313,
   "VolumeGroup": "Bottom",
   "Sell Thru": 36,
   "Sell ThruGroup": "None",
   "Remaining Inv": 869,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456798,
   "ProductName": "Dark Slim Jean",
   "Picture": "slimjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 50,
   "MarginGroup": "Top",
   "Volume": 542,
   "VolumeGroup": "None",
   "Sell Thru": 47,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 1153,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456799,
   "ProductName": "Light Slim Jean",
   "Picture": "lightslimjean.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "Light",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 47,
   "MarginGroup": "Top",
   "Volume": 649,
   "VolumeGroup": "None",
   "Sell Thru": 44,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1475,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456800,
   "ProductName": "Grey Faded Jean",
   "Picture": "grayfadedjean.jpg",
   "SubCategory": "Jeans",
   "Color": "Grey",
   "Style": "Straight",
   "Wash": "Faded",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 35,
   "MarginGroup": "None",
   "Volume": 330,
   "VolumeGroup": "Bottom",
   "Sell Thru": 32,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1031,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456801,
   "ProductName": "Light Faded Jean",
   "Picture": "lightfadedjean.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Faded",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 40,
   "MarginGroup": "None",
   "Volume": 529,
   "VolumeGroup": "None",
   "Sell Thru": 37,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1430,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456802,
   "ProductName": "Light Raw Jean",
   "Picture": "lightrippedraw.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "Light",
   "Details": "Ripped",
   "Vendor": "XYZ Vendor",
   "Margin": 34,
   "MarginGroup": "None",
   "Volume": 515,
   "VolumeGroup": "None",
   "Sell Thru": 31,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1661,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456803,
   "ProductName": "Light Twist Jean",
   "Picture": "lighttwist.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "Ripped",
   "Vendor": "XYZ Vendor",
   "Margin": 26,
   "MarginGroup": "None",
   "Volume": 234,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 1017,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456804,
   "ProductName": "Blue Basic Jean",
   "Picture": "bluebasicjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 22,
   "MarginGroup": "None",
   "Volume": 641,
   "VolumeGroup": "None",
   "Sell Thru": 40,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1603,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456805,
   "ProductName": "Dark Ripped Jean",
   "Picture": "darkrippedjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 22,
   "MarginGroup": "Top",
   "Volume": 611,
   "VolumeGroup": "None",
   "Sell Thru": 20,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 3055,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456806,
   "ProductName": "Desert Jean",
   "Picture": "desertjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 8,
   "MarginGroup": "None",
   "Volume": 328,
   "VolumeGroup": "Bottom",
   "Sell Thru": 65,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 505,
   "Remaining InvGroup": "None"
 },
 {
   "SKU": 523456807,
   "ProductName": "Embroidered Jean",
   "Picture": "embroideredjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "Patches",
   "Vendor": "123 Vendor",
   "Margin": 30,
   "MarginGroup": "Top",
   "Volume": 246,
   "VolumeGroup": "Bottom",
   "Sell Thru": 22,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1118,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456808,
   "ProductName": "Faded Jean",
   "Picture": "fadedjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Faded",
   "Details": "Ripped",
   "Vendor": "123 Vendor",
   "Margin": 30,
   "MarginGroup": "Bottom",
   "Volume": 103,
   "VolumeGroup": "Bottom",
   "Sell Thru": 46,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 224,
   "Remaining InvGroup": "Bottom"
 },
 {
   "SKU": 523456809,
   "ProductName": "Grey Faded Jean",
   "Picture": "grayfadedjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Grey",
   "Style": "Straight",
   "Wash": "Faded",
   "Details": "Ripped",
   "Vendor": "123 Vendor",
   "Margin": 30,
   "MarginGroup": "Top",
   "Volume": 422,
   "VolumeGroup": "Bottom",
   "Sell Thru": 35,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 1206,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456810,
   "ProductName": "Grey Jean",
   "Picture": "grayjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Grey",
   "Style": "Straight",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 23,
   "MarginGroup": "Bottom",
   "Volume": 152,
   "VolumeGroup": "Bottom",
   "Sell Thru": 65,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 234,
   "Remaining InvGroup": "Bottom"
 },
 {
   "SKU": 523456811,
   "ProductName": "Grey Slim Jean",
   "Picture": "grayslimtfit.jpg",
   "SubCategory": "Jeans",
   "Color": "Grey",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 24,
   "MarginGroup": "Top",
   "Volume": 710,
   "VolumeGroup": "None",
   "Sell Thru": 22,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 3227,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456812,
   "ProductName": "Kneecap Jean",
   "Picture": "kneecapjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "Ripped, Patches",
   "Vendor": "ABC Vendor",
   "Margin": 45,
   "MarginGroup": "None",
   "Volume": 436,
   "VolumeGroup": "Bottom",
   "Sell Thru": 46,
   "Sell ThruGroup": "None",
   "Remaining Inv": 948,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456813,
   "ProductName": "Light Blue Jean",
   "Picture": "lightbluejeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 66,
   "MarginGroup": "None",
   "Volume": 792,
   "VolumeGroup": "Top",
   "Sell Thru": 33,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 2400,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456814,
   "ProductName": "Light Ripped Jean",
   "Picture": "lightrippedjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "Ripped",
   "Vendor": "ABC Vendor",
   "Margin": 30,
   "MarginGroup": "Bottom",
   "Volume": 233,
   "VolumeGroup": "Bottom",
   "Sell Thru": 87,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 268,
   "Remaining InvGroup": "Bottom"
 },
 {
   "SKU": 523456815,
   "ProductName": "Patches Jean",
   "Picture": "patchesjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "Dark",
   "Details": "Ripped, Patches",
   "Vendor": "ABC Vendor",
   "Margin": 30,
   "MarginGroup": "Bottom",
   "Volume": 938,
   "VolumeGroup": "Top",
   "Sell Thru": 88,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 1066,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456816,
   "ProductName": "Raw Ripped Jean",
   "Picture": "rawrippedjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "Ripped",
   "Vendor": "ABC Vendor",
   "Margin": 30,
   "MarginGroup": "None",
   "Volume": 100,
   "VolumeGroup": "Bottom",
   "Sell Thru": 43,
   "Sell ThruGroup": "None",
   "Remaining Inv": 233,
   "Remaining InvGroup": "Bottom"
 },
 {
   "SKU": 523456817,
   "ProductName": "Ripped Pleated Jean",
   "Picture": "rippedpleatsjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "Mid",
   "Details": "Ripped",
   "Vendor": "ABC Vendor",
   "Margin": 23,
   "MarginGroup": "Top",
   "Volume": 577,
   "VolumeGroup": "None",
   "Sell Thru": 11,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 5245,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456818,
   "ProductName": "Slim Dark Jean",
   "Picture": "slimdarkbluejeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Dark",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 23,
   "MarginGroup": "Top",
   "Volume": 186,
   "VolumeGroup": "Bottom",
   "Sell Thru": 43,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 433,
   "Remaining InvGroup": "Bottom"
 },
 {
   "SKU": 523456819,
   "ProductName": "Slimfit White Jean",
   "Picture": "slimfitwhite.jpg",
   "SubCategory": "Jeans",
   "Color": "White",
   "Style": "Slim",
   "Wash": "Light",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 18,
   "MarginGroup": "None",
   "Volume": 615,
   "VolumeGroup": "None",
   "Sell Thru": 21,
   "Sell ThruGroup": "None",
   "Remaining Inv": 2929,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456820,
   "ProductName": "Carrot Fit Jean",
   "Picture": "slimjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 11,
   "MarginGroup": "None",
   "Volume": 319,
   "VolumeGroup": "Bottom",
   "Sell Thru": 10,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 3190,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456821,
   "ProductName": "Studio Jean",
   "Picture": "studiojeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "",
   "Vendor": "789 Vendor",
   "Margin": 23,
   "MarginGroup": "None",
   "Volume": 829,
   "VolumeGroup": "Top",
   "Sell Thru": 13,
   "Sell ThruGroup": "None",
   "Remaining Inv": 6377,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456822,
   "ProductName": "Twist Jean",
   "Picture": "twistjeans.jpg",
   "SubCategory": "Jeans",
   "Color": "Blue",
   "Style": "Straight",
   "Wash": "Mid",
   "Details": "Ripped",
   "Vendor": "789 Vendor",
   "Margin": 24,
   "MarginGroup": "None",
   "Volume": 40,
   "VolumeGroup": "Bottom",
   "Sell Thru": 15,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 267,
   "Remaining InvGroup": "Bottom"
 },
 {
   "SKU": 523456823,
   "ProductName": "White Ripped Jean",
   "Picture": "whiteripped.jpg",
   "SubCategory": "Jeans",
   "Color": "White",
   "Style": "Straight",
   "Wash": "Light",
   "Details": "Ripped",
   "Vendor": "789 Vendor",
   "Margin": 35,
   "MarginGroup": "None",
   "Volume": 372,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 1617,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456824,
   "ProductName": "Blue Jogger",
   "Picture": "bluejogger.jpg",
   "SubCategory": "Joggers",
   "Color": "Blue",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "Linen",
   "Vendor": "789 Vendor",
   "Margin": 34,
   "MarginGroup": "Top",
   "Volume": 139,
   "VolumeGroup": "Bottom",
   "Sell Thru": 24,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 579,
   "Remaining InvGroup": "None"
 },
 {
   "SKU": 523456825,
   "ProductName": "Grey Plush Jogger",
   "Picture": "grayplushjoggers.jpg",
   "SubCategory": "Joggers",
   "Color": "Grey",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "Plush",
   "Vendor": "789 Vendor",
   "Margin": 25,
   "MarginGroup": "None",
   "Volume": 31,
   "VolumeGroup": "Bottom",
   "Sell Thru": 51,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 61,
   "Remaining InvGroup": "Bottom"
 },
 {
   "SKU": 523456826,
   "ProductName": "Grey Jogger",
   "Picture": "jogger.jpg",
   "SubCategory": "Joggers",
   "Color": "Grey",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "Linen",
   "Vendor": "789 Vendor",
   "Margin": 34,
   "MarginGroup": "Top",
   "Volume": 211,
   "VolumeGroup": "Bottom",
   "Sell Thru": 34,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 621,
   "Remaining InvGroup": "None"
 },
 {
   "SKU": 523456827,
   "ProductName": "Pleated Jogger",
   "Picture": "pleated.jpg",
   "SubCategory": "Joggers",
   "Color": "Blue",
   "Style": "Cropped",
   "Wash": "None",
   "Details": "Linen",
   "Vendor": "789 Vendor",
   "Margin": 23,
   "MarginGroup": "Bottom",
   "Volume": 50,
   "VolumeGroup": "Bottom",
   "Sell Thru": 34,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 147,
   "Remaining InvGroup": "Bottom"
 },
 {
   "SKU": 523456828,
   "ProductName": "Tech Jogger",
   "Picture": "techjogger.jpg",
   "SubCategory": "Joggers",
   "Color": "Black",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "Cotton",
   "Vendor": "789 Vendor",
   "Margin": 23,
   "MarginGroup": "Top",
   "Volume": 219,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 952,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456829,
   "ProductName": "White Jogger",
   "Picture": "whitejogger.jpg",
   "SubCategory": "Joggers",
   "Color": "White",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "Linen",
   "Vendor": "ABC Vendor",
   "Margin": 23,
   "MarginGroup": "Bottom",
   "Volume": 264,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1148,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456830,
   "ProductName": "Zip Jogger",
   "Picture": "zipjogger.jpg",
   "SubCategory": "Joggers",
   "Color": "Blue",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "Zippers",
   "Vendor": "ABC Vendor",
   "Margin": 24,
   "MarginGroup": "Top",
   "Volume": 736,
   "VolumeGroup": "None",
   "Sell Thru": 23,
   "Sell ThruGroup": "None",
   "Remaining Inv": 3200,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456831,
   "ProductName": "Blue Suit Pant",
   "Picture": "bluesuit.jpg",
   "SubCategory": "Suits",
   "Color": "Blue",
   "Style": "Pleated",
   "Wash": "None",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 25,
   "MarginGroup": "None",
   "Volume": 652,
   "VolumeGroup": "None",
   "Sell Thru": 85,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 767,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456832,
   "ProductName": "Checked Suit Pant",
   "Picture": "checked.jpg",
   "SubCategory": "Suits",
   "Color": "Blue",
   "Style": "Cropped",
   "Wash": "None",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 26,
   "MarginGroup": "None",
   "Volume": 371,
   "VolumeGroup": "Bottom",
   "Sell Thru": 30,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 1237,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456833,
   "ProductName": "Checked Suit Pant",
   "Picture": "checkedsuit.jpg",
   "SubCategory": "Suits",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "None",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 13,
   "MarginGroup": "Bottom",
   "Volume": 357,
   "VolumeGroup": "Bottom",
   "Sell Thru": 66,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 541,
   "Remaining InvGroup": "None"
 },
 {
   "SKU": 523456834,
   "ProductName": "Contrasting Suit Pant",
   "Picture": "contrastingsuit.jpg",
   "SubCategory": "Suits",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "None",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 15,
   "MarginGroup": "Bottom",
   "Volume": 201,
   "VolumeGroup": "Bottom",
   "Sell Thru": 43,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 467,
   "Remaining InvGroup": "None"
 },
 {
   "SKU": 523456835,
   "ProductName": "Skull Suit Pant",
   "Picture": "skullsuit.jpg",
   "SubCategory": "Suits",
   "Color": "Pattern",
   "Style": "Cropped",
   "Wash": "None",
   "Details": "",
   "Vendor": "ABC Vendor",
   "Margin": 25,
   "MarginGroup": "None",
   "Volume": 325,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1413,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456836,
   "ProductName": "Camo Trouser",
   "Picture": "camotrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Pattern",
   "Style": "Straight",
   "Wash": "None",
   "Details": "Camo",
   "Vendor": "ABC Vendor",
   "Margin": 23,
   "MarginGroup": "Top",
   "Volume": 1369,
   "VolumeGroup": "Top",
   "Sell Thru": 24,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 5704,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456837,
   "ProductName": "Khaki Chino",
   "Picture": "chinokhalki.jpg",
   "SubCategory": "Trousers",
   "Color": "Tan",
   "Style": "Straight",
   "Wash": "None",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 34,
   "MarginGroup": "Top",
   "Volume": 520,
   "VolumeGroup": "None",
   "Sell Thru": 56,
   "Sell ThruGroup": "None",
   "Remaining Inv": 929,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456838,
   "ProductName": "Denim Chino",
   "Picture": "denimchinos.jpg",
   "SubCategory": "Trousers",
   "Color": "Green",
   "Style": "Straight",
   "Wash": "None",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 24,
   "MarginGroup": "None",
   "Volume": 927,
   "VolumeGroup": "Top",
   "Sell Thru": 34,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 2726,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456839,
   "ProductName": "Grey Trouser",
   "Picture": "graytrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Grey",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Cuffed",
   "Vendor": "123 Vendor",
   "Margin": 25,
   "MarginGroup": "None",
   "Volume": 806,
   "VolumeGroup": "Top",
   "Sell Thru": 25,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 3224,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456840,
   "ProductName": "Khaki Zip Trouser",
   "Picture": "khalkizips.jpg",
   "SubCategory": "Trousers",
   "Color": "Green",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Zippers",
   "Vendor": "123 Vendor",
   "Margin": 35,
   "MarginGroup": "None",
   "Volume": 326,
   "VolumeGroup": "Bottom",
   "Sell Thru": 13,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 2508,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456841,
   "ProductName": "Lavender Trouser",
   "Picture": "lavendertrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Blue",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Cuffed",
   "Vendor": "123 Vendor",
   "Margin": 23,
   "MarginGroup": "None",
   "Volume": 136,
   "VolumeGroup": "Bottom",
   "Sell Thru": 9,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1511,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456842,
   "ProductName": "Plush Trouser",
   "Picture": "plushtrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Blue",
   "Style": "Tie-waist",
   "Wash": "None",
   "Details": "",
   "Vendor": "123 Vendor",
   "Margin": 43,
   "MarginGroup": "None",
   "Volume": 254,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "None",
   "Remaining Inv": 1104,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456843,
   "ProductName": "Red Trouser",
   "Picture": "redtrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Red",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Cuffed",
   "Vendor": "XYZ Vendor",
   "Margin": 24,
   "MarginGroup": "Top",
   "Volume": 277,
   "VolumeGroup": "Bottom",
   "Sell Thru": 45,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 616,
   "Remaining InvGroup": "None"
 },
 {
   "SKU": 523456844,
   "ProductName": "Seersucker Suit",
   "Picture": "seersucker.jpg",
   "SubCategory": "Suits",
   "Color": "Blue",
   "Style": "Cropped",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 35,
   "MarginGroup": "None",
   "Volume": 189,
   "VolumeGroup": "Bottom",
   "Sell Thru": 34,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 556,
   "Remaining InvGroup": "None"
 },
 {
   "SKU": 523456845,
   "ProductName": "Pink Skinny Trouser",
   "Picture": "skinnytrouserpink.jpg",
   "SubCategory": "Trousers",
   "Color": "Pink",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Cuffed",
   "Vendor": "XYZ Vendor",
   "Margin": 55,
   "MarginGroup": "Top",
   "Volume": 170,
   "VolumeGroup": "Bottom",
   "Sell Thru": 2,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 8500,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456846,
   "ProductName": "Blue Skinny Trouser",
   "Picture": "skinnytrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Blue",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Cuffed",
   "Vendor": "XYZ Vendor",
   "Margin": 33,
   "MarginGroup": "Bottom",
   "Volume": 166,
   "VolumeGroup": "Bottom",
   "Sell Thru": 45,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 369,
   "Remaining InvGroup": "Bottom"
 },
 {
   "SKU": 523456847,
   "ProductName": "Slim Dark Trouser",
   "Picture": "slimfitdark.jpg",
   "SubCategory": "Trousers",
   "Color": "Black",
   "Style": "Slim",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 10,
   "MarginGroup": "Top",
   "Volume": 220,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "None",
   "Remaining Inv": 957,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456848,
   "ProductName": "Slim Grey Trouser",
   "Picture": "slimfitgray.jpg",
   "SubCategory": "Trousers",
   "Color": "Grey",
   "Style": "Slim",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 13,
   "MarginGroup": "Bottom",
   "Volume": 492,
   "VolumeGroup": "None",
   "Sell Thru": 22,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 2236,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456849,
   "ProductName": "Slim Navy Trouser",
   "Picture": "slimfitnavy.jpg",
   "SubCategory": "Trousers",
   "Color": "Blue",
   "Style": "Slim",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 13,
   "MarginGroup": "Top",
   "Volume": 392,
   "VolumeGroup": "Bottom",
   "Sell Thru": 11,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 3564,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456850,
   "ProductName": "Slim Tan Trouser",
   "Picture": "slimfittan.jpg",
   "SubCategory": "Trousers",
   "Color": "Tan",
   "Style": "Slim",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 13,
   "MarginGroup": "None",
   "Volume": 20,
   "VolumeGroup": "Bottom",
   "Sell Thru": 8,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 250,
   "Remaining InvGroup": "Bottom"
 },
 {
   "SKU": 523456851,
   "ProductName": "Slim Tan Chino",
   "Picture": "tanchinos.jpg",
   "SubCategory": "Trousers",
   "Color": "Tan",
   "Style": "Cropped",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 14,
   "MarginGroup": "None",
   "Volume": 636,
   "VolumeGroup": "None",
   "Sell Thru": 55,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 1156,
   "Remaining InvGroup": "Top"
 },
 {
   "SKU": 523456852,
   "ProductName": "Tan Trouser",
   "Picture": "tantrousers.jpg",
   "SubCategory": "Trousers",
   "Color": "Tan",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "Cuffed",
   "Vendor": "XYZ Vendor",
   "Margin": 15,
   "MarginGroup": "Bottom",
   "Volume": 351,
   "VolumeGroup": "Bottom",
   "Sell Thru": 76,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 462,
   "Remaining InvGroup": "None"
 },
 {
   "SKU": 523456853,
   "ProductName": "White Trouser",
   "Picture": "white.jpg",
   "SubCategory": "Trousers",
   "Color": "White",
   "Style": "Straight",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 15,
   "MarginGroup": "Bottom",
   "Volume": 127,
   "VolumeGroup": "Bottom",
   "Sell Thru": 90,
   "Sell ThruGroup": "Bottom",
   "Remaining Inv": 141,
   "Remaining InvGroup": "Bottom"
 },
 {
   "SKU": 523456854,
   "ProductName": "White Zip Trouser",
   "Picture": "whitezips.jpg",
   "SubCategory": "Trousers",
   "Color": "Green",
   "Style": "Skinny",
   "Wash": "None",
   "Details": "",
   "Vendor": "XYZ Vendor",
   "Margin": 15,
   "MarginGroup": "None",
   "Volume": 135,
   "VolumeGroup": "Bottom",
   "Sell Thru": 23,
   "Sell ThruGroup": "Top",
   "Remaining Inv": 587,
   "Remaining InvGroup": "None"
 }
]}

var lookUpFilter = {
    "Jeans":{"type":"SubCategory","info":"Jeans"},
    "Suits":{"type":"SubCategory","info":"Suits"},
    "Trousers":{"type":"SubCategory","info":"Trousers"},
    "Joggers":{"type":"SubCategory","info":"Joggers"},
    
    "Volume Top 20%":{"type":"VolumeGroup","info":"Top"},
    "Volume Bottom 20%":{"type":"VolumeGroup","info":"Bottom"},
    
    "Margin Top 20%":{"type":"MarginGroup","info":"Top"},
    "Margin Bottom 20%":{"type":"MarginGroup","info":"Bottom"},
    
    "Sell Thru Top 20%":{"type":"Sell ThruGroup","info":"Top"},
    "Sell Thru Bottom 20%":{"type":"Sell ThruGroup","info":"Bottom"},
    
    "Remaining Inv Top 20%":{"type":"Remaining InvGroup","info":"Top"},
    "Remaining Inv Bottom 20%":{"type":"Remaining InvGroup","info":"Bottom"},
    
    "Black":{"type":"Color","info":"Black"},
    "White":{"type":"Color","info":"White"},
    "Grey":{"type":"Color","info":"Grey"},
    "Tan":{"type":"Color","info":"Tan"},
    "Blue":{"type":"Color","info":"Blue"},
    "Green":{"type":"Color","info":"Green"},
    "Red":{"type":"Color","info":"Red"},
    "Pattern":{"type":"Color","info":"Pattern"},
    
    "Slim":{"type":"Style","info":"Slim"},
    "Skinny":{"type":"Style","info":"Skinny"},
    "Straight":{"type":"Style","info":"Straight"},
    "Bootcut":{"type":"Style","info":"Bootcut"},
    "Cropped":{"type":"Style","info":"Cropped"},
    
    "Rinse":{"type":"Wash","info":"Rinse"},
    "Mid":{"type":"Wash","info":"Mid"},
    "Light":{"type":"Wash","info":"Light"},
    "Faded":{"type":"Wash","info":"Faded"},
    
    "XYZ Vendor":{"type":"Vendor","info":"XYZ Vendor"},
    "ABC Vendor":{"type":"Vendor","info":"ABC Vendor"},
    "123 Vendor":{"type":"Vendor","info":"123 Vendor"},
    "789 Vendor":{"type":"Vendor","info":"789 Vendor"},

}

var lookUpOrder ={
   "Volume High to Low":{"type": "Volume", "direction":"Descending"},
    "Volume Low to High":{"type": "Volume", "direction":"Ascending"},
    
    "Margin High to Low":{"type": "Margin", "direction":"Descending"},
    "Margin Low to High":{"type": "Margin", "direction":"Ascending"},
    
    "Sell Thru High to Low":{"type": "Sell Thru", "direction":"Descending"},
    "Sell Thru Low to High":{"type": "Sell Thru", "direction":"Ascending"},
    
    "Remaining Inv High to Low":{"type": "Remaining Inv", "direction":"Descending"},
    "Remaining Inv Low to High":{"type": "Remaining Inv", "direction":"Ascending"},
    
    "Color":{"type": "Color", "direction":"Group"},
    "Style":{"type": "Style", "direction":"Group"},
    "Wash":{"type": "Wash", "direction":"Group"},
    
    "Group by vendor":{"type": "Vendor", "direction":"Group"},
    
}



